"""Reemplazar es_super_usuario por rol

Revision ID: 91aa931a9035
Revises: 9b7a93cf9ba9
Create Date: 2025-06-27 22:54:47.972228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91aa931a9035'
down_revision = '9b7a93cf9ba9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captura', 'remitente_id')
    op.alter_column('directorio_interno', 'cargo',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.drop_index(op.f('nombre'), table_name='directorio_interno')
    op.add_column('usuarios', sa.Column('rol', sa.String(length=50), nullable=False))
    op.alter_column('usuarios', 'usuario',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('usuarios', 'contrasena',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.drop_column('usuarios', 'es_super_usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('es_super_usuario', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('usuarios', 'contrasena',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('usuarios', 'usuario',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.drop_column('usuarios', 'rol')
    op.create_index(op.f('nombre'), 'directorio_interno', ['nombre'], unique=True)
    op.alter_column('directorio_interno', 'cargo',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.add_column('captura', sa.Column('remitente_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
